global:
  scrape_interval: 15s
  evaluation_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - localhost:9093

rule_files:
  - alert-rules-exam-prep-1.yml

scrape_configs:
  - job_name: 'exam-prep-1'
    metrics_path: /probe
    static_configs:
      - targets:
          - http://softunibazar-alwa21948.azurewebsites.net/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115

